### ISSUE TITLE
Using this for a standalone Node.js server?

### ISSUE THREAD

**Issue by KamuelaFranco** [aliemteam/wp-graphql#2]
Any recipe or pointers for using this server side as a layer between the WP REST API and the front end? I would like to use AWS Lambda and API caching to hopefully speed up a GraphQL server.

**Comment by dsifford** [comment]
Hi @KamuelaFranco 

As a quick preface: The library is still under heavy development, so the API is subject to change.

Having said that, can you explain your use-case a bit more? 

I'm not super familiar with lambda gateway caching, but I assume AWS is responsible for determining whether or not to return cache or fresh data based on the request URL (and perhaps query params?). I also assume it's something that works passively on its own in the background without you having to actually choose what to cache or not?

If those assumptions are correct, then you should be able to use this completely as-is in your lambda function. Either way, because your endpoint is a PHP server without built-in GraphQL support, you're going to have to make a few round trips. You should still get the benefit of API gateway caching because under the hood, this library just makes REST calls.

The only way to avoid the roundtrips would be to write your GraphQL schema entirely on the WordPress server in PHP (which is something we actually explored, but it ended up being a gigantic pain).

**Comment by KamuelaFranco** [comment]
Yes, I realised that your library will actually work 100% as-is so long as there's one more layer of network request handling involved, e.g. between the real front-end client and this new GraphQL layer.

**Comment by dsifford** [comment]
Awesome! Marking this as resolved. Feel free to chime back with any questions. 

Also, please let me know if you have any feedback/suggestions with how everything works. I just published this repo to npm a few days ago so you're probably the first person other than us to use it.
