### ISSUE TITLE
Does this work with any exposed endpoints?

### ISSUE THREAD

**Issue by corysimmons** [aliemteam/wp-graphql#7]
For instance, would this work with https://wordpress.org/plugins/acf-to-rest-api/

**Comment by dsifford** [comment]
You'd have to extend the schema for it to work with non-standard REST endpoints. 

Just a warning up front though: WordPress changed their API to now only allow access to authenticated write methods from admin users. So regardless if you use a key-based authentication, if a user is logged in with non-admin credentials, the API will fail silently.

Our team stopped using the REST API because of this.

**Comment by corysimmons** [comment]
>WordPress changed their API to now only allow access to authenticated write methods from admin users.

Do you happen to have any more resources on this? I'd like to read the debate and specific implications of this.

>Our team stopped using the REST API because of this.

Out of curiosity, what did you move to?

**Comment by corysimmons** [comment]
Also, did you guys investigate Rooftop for this? https://rooftopcms.readme.io/docs/authentication

**Comment by dsifford** [comment]
> Do you happen to have any more resources on this? I'd like to read the debate and specific implications of this.

Unfortunately, no. Their REST page isn't very clear on this either. 

To give you an idea of why it failed to meet our needs:

We specifically created this repo for a circumstance where we needed to create a custom dashboard for a user to manage subordinates (we were/are using React for this). The dashboard needed to pull in various meta fields from each of their subordinate's usermeta and display it on the dashboard. The issue though is that because the managing user is not an "Administrator" user, they can't pull in other user's metadata (including read-only data!), even if the API is called programatically using basic authentication using an administrative-level API token.

If this sounds crazy to you, you're not alone. This fundamentally made the API useless for us because you are unable to access even the most basic of data without yourself (the logged in user) being an administrator.

> Out of curiosity, what did you move to?

For non-secure data, we're just dumping it to the global scope using `wp_localize_script`. For secure data, we're accessing it using ajax.

> Also, did you guys investigate Rooftop for this? 

Haven't heard of that before, so no. But that looks interesting from first glance. I'm wondering how they're able to bypass the issues we've ran into.

We used [Basic Auth](https://github.com/WP-API/Basic-Auth).

**Comment by corysimmons** [comment]
Thanks for the context!

**Comment by corysimmons** [comment]
@dsifford Do you care if I email/Discord you for more context? I'm trying to pick a good default stack, clients love WordPress, and just have a bunch of small questions. 😬

**Comment by dsifford** [comment]
Sure. Happy to help clarify where I can.

dereksifford@gmail.com
